# ===============================
# datasource - postgresql (neon)
# ===============================
spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# jpa / hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# opcional (logging sql)
# ===============================

logging.level.root=info
logging.level.com.jdcolorado.gestions.eventos=debug
logging.level.org.springframework=info
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
# ===============================
# eliminar h2 (no se esta usando)
# ===============================
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true
# spring.h2.console.settings.trace=true