spring.application.name=gestionEventosApi
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mi_clave_super_larga_y_segura_para_firmar_tokens_123456mi_clave_super_larga_y_segura_para_firmar_tokens_123456mi_clave_super_larga_y_segura_para_firmar_tokens_123456
jwt.expiration=600000